DASHBASE-74 Update chart for dashbase and logmatters
dashbase/dashbase-k8s pull request #288
Opened 2021-04-13 07:46 UTC by cuichenli

1. dashbase - Update statefulset `Kafka's default secrets 
2. logmatters - add option to enable ssl and mount secret file

2021-04-13 08:18 UTC, sincejune commented on dashbase/values.yaml
> +        kafka-keystore:
you'll need to rollback this.

2021-04-13 08:21 UTC, sincejune requested changes

2021-04-13 08:21 UTC, sincejune commented on dashbase/values.yaml
> +        kafka-keystore-password:
ditto

2021-04-13 08:21 UTC, sincejune commented on dashbase-logmatters/templates/StatefulSet.yaml
> +            secretName: kafka-client
You can add an `optional` parameter to declare the secret is not necessary. So that we don't need another flag in values.yml.

ref: https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/volume/#Volume

2021-04-13 08:29 UTC, sincejune commented on dashbase/values.yaml
> +        kafka-keystore:
In the very old architecture, dashbase components used these keys to ingest data from Kafka. And I believe the architecture is still being used.

If we need to change the keys used in Kafka, we'd better change the content which the secret has.

2021-04-13 08:52 UTC, cuichenli commented on dashbase-logmatters/templates/StatefulSet.yaml
> +            secretName: kafka-client
done

2021-04-13 08:52 UTC, cuichenli commented on dashbase/values.yaml
> +        kafka-keystore-password:
done

2021-04-13 08:52 UTC, cuichenli commented on dashbase/values.yaml
> +        kafka-keystore:
done

2021-04-14 03:23 UTC, sincejune approved these changes
LGTM

2021-04-14 03:23 UTC, sincejune commented on dashbase-logmatters/templates/StatefulSet.yaml
> +            secretName: kafka-client
I think it would be better to rename the secret `kafka-client` to a meaningful one

2021-04-14 05:53 UTC, cuichenli commented on dashbase-logmatters/templates/StatefulSet.yaml
> +            secretName: kafka-client
Renamed it to be aligned with https://github.com/dashbase/dashbase-installation/commit/0e84439c30a42ebb18f205cc3f4661e87015e543

2021-04-15 01:05 UTC, merged